# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  grafonnet_generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update grafana json file
        run: |
          sudo podman run --rm -d --name run_grafonnet -v /grafonnet_generator/grafana:/app --privileged quay.io/ebattat/run_grafonnet

      - name: Check for changes in grafana json file
        id: check_changes
        run: |
            git diff --quiet || echo "::set-output name=changes::true"

      - name: commit grafana json file
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git checkout main
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name  ${{ secrets.USER_NAME }}
          git add grafonnet_generator/grafana/output.json
          git commit -m "Update grafana json file"
          git push
