name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  grafonnet_generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run grafana json container generator
        run: |
          sudo docker run --rm --name run_grafonnet -v $GITHUB_WORKSPACE/grafana:/app --privileged quay.io/ebattat/run_grafonnet:latest

      - name: Set GIT_DIFF environment variable
        run: |
          # Store the result of git diff in the GIT_DIFF environment variable
          GIT_DIFF=$(git diff --quiet $GITHUB_WORKSPACE/grafana/output.json || echo "true")
          echo "GIT_DIFF=$GIT_DIFF" >> $GITHUB_ENV
      

      - name: debug ENV
        run: |
          echo "GIT_DIFF = $GIT_DIFF"
          echo ${{env.GIT_DIFF}} 

      - name: Update Grafana dashboard with new json
        if: env.GIT_DIFF == 'true'
        env:
          PERF_GRAFANA_URL: ${{ secrets.PERF_GRAFANA_URL }}
          PERF_GRAFANA_API_KEY: ${{ secrets.PERF_GRAFANA_API_KEY }}
          PERF_GRAFANA_JSON: grafana/output.json
        run: python $GITHUB_WORKSPACE/grafana/update_grafana_dashboard.py

      - name: Commit grafana json file after update version
        if: env.GIT_DIFF == 'true'
        run: |
          echo ${{ steps.check_changes.outputs.changes }}
          git checkout main
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name  ${{ secrets.USER_NAME }}
          git add $GITHUB_WORKSPACE/grafana/output.json
          git commit -m "Update grafana json file"

          # Pull the latest changes from the remote main branch
          git pull origin main

          # Push the changes to the remote main branch
          git push
