
name: Deploy Perf Env Nightly CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  workload:
    name: workload
    runs-on: ubuntu-latest
    strategy:
       # run one job every time
       max-parallel: 1
       # continue to next job if failed
       fail-fast: false
       matrix:
          workload:
              - 'vdbench_vm'
              - 'vdbench_pod_scale'
              - 'vdbench_kata_scale'
              - 'vdbench_vm_scale'
              - 'clusterbuster'
              - 'bootstorm_vm_scale'
              - 'windows_vm_scale_windows10'
              - 'windows_vm_scale_windows11'
              - 'windows_vm_scale_windows_server_2019'
              - 'windows_vm_scale_windows_server_2022'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: ✔️ Run workload ${{ matrix.workload }}
      run: |
        echo '>>>>>>>>>>>>>>>>>>>>>>>>>> Start E2E workload: ${{ matrix.workload }} >>>>>>>>>>>>>>>>>>>>>>>>>>'
